### ISSUE TITLE
article spanning multiple columns

### ISSUE THREAD

**Issue by Temitope-Emmanuel** [jscancella/NYTribuneOCRExperiments#2]
I'm trying to use the [find_Text_usingSums workflow](https://github.com/jscancella/NYTribuneOCRExperiments?tab=readme-ov-file#process-workflow-for-findtext_usingsumspy), but I have a problem that I have articles spanning multiple columns, how do I go about this, the current iteration is not working
![PM News October_28_1994_ Pg 2 resize](https://github.com/jscancella/NYTribuneOCRExperiments/assets/47703196/167816e7-be03-48a2-8f57-24d772dc7d12)

**Comment by jscancella** [comment]
This was just an experiment to prove it could work, and not a production ready solution. This example image would not be a good candidate since it is skewed and the find columns by sums assumes that there is no skew.

You would be better off training a [YOLO](https://github.com/ultralytics/yolov5.git) model. I did experiment with it (https://github.com/jscancella/chronam_with_yolo/blob/master/Chronam%20column%20detection%20with%20YOLOv5.ipynb) but it is not a step by step walkthrough.

**Comment by Temitope-Emmanuel** [comment]
Okay @jscancella , thank you, I will check it out!!!
P.S. sorry for the late reply.
